#!/system/bin/sh
#################################################################################################################
# Got inspiration from a cm9 rom for one v.                                                                     #
# Dont know the name of the dev, but used                                                                       #
# That as a template to make this.                                                                              #
# So credits to that guy :)                                                                                     #
#                                                                                                               #
# If you want a diffrent swappiness change the value here : echo "vm.swappiness=XX" >> /etc/sysctl.conf         #
# If you want bigger or smaller swap file change this : dd if=/dev/zero of=/data/swapfile bs=1024 count=XXXXXX  #
# In both its the X value that needs to be changed.                                                             #
#														#
# You are welcome to use this, but remember credits, and dont remove this section.    				#
#														#
# v.1.1 fixed swappiness value not being set.					                                #
#################################################################################################################
log -p i -t start "    Making swap and enables it";
log -p i -t start "    By Anders3408";

SWAP_SIZE=130160
SWAPPINESS=60

LOG_FILE=/data/swap.log
if [ -e $LOG_FILE ]; then
    rm $LOG_FILE
fi

echo "Starting swap set $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE

if [ ! -e /system/xbin/busybox ]; then
	echo "busybox not installed" | tee -a $LOG_FILE
	exit -1
fi

# enable swap prtition 130m
/system/xbin/busybox mkswap /dev/block/mmcblk0p29 | tee -a $LOG_FILE

# enable swap file on /data
CREATE_DATA_SWAPFILE=1

# mount /data if needed
if [ -e /data ]; then
	# check if already mounted
	cat /proc/mounts |grep mmcblk0p29 &> /dev/null
	
	if [ $? -eq 1 ]; then
		# not mounted till now
		busybox mount -t ext4 -o nosuid,nodev /dev/block/mmcblk0p29 /data
		if [ $? -eq 1 ]; then
			echo "failed to mount /dev/block/mmcblk0p29 to /data" | tee -a $LOG_FILE	
			CREATE_DATA_SWAPFILE=0
		fi
	else
		# mounted - check if its an ext partition	
		cat /proc/mounts |grep mmcblk0p29 | grep ext4 &> /dev/null
		if [ $? -eq 1 ]; then
			echo "/data is not an ext4 partition" | tee -a $LOG_FILE	
			CREATE_DATA_SWAPFILE=0
		fi
	fi
else 
	echo "/data not found" | tee -a $LOG_FILE
	CREATE_DATA_SWAPFILE=0
fi

if [ $CREATE_DATA_SWAPFILE -eq 1 ]; then
	if [ -e /data ]; then
		if [ -e /data/swapfile ]; then
			rm /data/swapfile
		fi

		# 128 mb
		dd if=/dev/zero of=/data/swapfile bs=1024 count=$SWAP_SIZE | tee -a $LOG_FILE
                chmod 600 /data/swapfile | tee -a $LOG_FILE
		/system/xbin/busybox mkswap /data/swapfile | tee -a $LOG_FILE
		/system/xbin/busybox swapon /data/swapfile | tee -a $LOG_FILE
	fi
fi
sysctl -w vm.swappiness=$SWAPPINESS | tee -a $LOG_FILE
/system/xbin/busybox swapon /dev/block/mmcblk0p29 | tee -a $LOG_FILE
/system/xbin/busybox free | tee -a $LOG_FILE
cat /proc/swaps | tee -a $LOG_FILE
echo "Ending swap set $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE
